#!/bin/sh

## A quick hack to deploy a generated website onto a Github repository, to be served as static content by github pages.  This is an example of a very bad shell script.

# This should only be run from the root of the gitbook project
# Replace the remote Github URL to use this on a different project

# Generate the live website
lein run content/config.edn

# Deploy new build
cd public/blog && rm -rf .git && git init && git add . && git commit -m "initial commit" && git branch -m live gh-pages && git remote add practicalli git@github.com:practicalli/blog.git && git push -f practicalli gh-pages
