* Practicalli Blog Content

A Cryogen project containing the raw markdown content that is used to generate the [[https://practicalli.github.io/blog][Practicalli blog website]]

A detailed description of putting this site together can be found in

[[https://practicalli.github.io/blog/posts/clojure-powered-blogging-with-cryogen/][Clojure powered blogging with Cryogent]] explains in detail how this project was developed.  Here is just the essential information.

** Local website

Run a local server that generates the website

#+BEGIN_SRC shell
clojure -X:serve
#+END_SRC

This generates all the files for the website in the ~public~ directory

** GitHub Actions Deployment
Pull requests are automatically built and deployed to https://practical.li/blog-staging/ to assist with reviewing articles.  The Publish Blog Staging GitHub workflow uses the [[https://github.com/JamesIves/github-pages-deploy-action][GitHub Pages Deploy Action]] with the Practicalli Organisation secret `CRYOGEN_PUBLISH_TOKEN` to push commits to the `gh-pages` branch of the practicalli/blog-staging repository.

Merged pull request and commits to the default branch will deploy to https://practical.li/blog/

** Suggestions / issues / bugs
Suggestions for posts, should be issues or bugs  [[https://practicalli.github.io/blog][Practicalli blog website]] reported as an issue on the practicalli/blog-content repository] should be reported as an issue or pull request on the practicalli/blog-content repository.

Deployment of the blog is not automated at the moment, but an updated site will be manually generated once any pull request is accepted by the maintainers.
