name: Publish Blog Staging

on: [pull_request]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 'Cache Clojure Dependencies'
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: cache-clojure-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: cache-clojure-deps-

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1165

      - name: Build Blog site
        run: clojure -M:build content/config-staging.edn

      - name: Publish to GitHub Pages
        # Publish to a separate repository as GitHub pages can only be served from one branch
        # Requires developer token as deploying across repositories
        uses: JamesIves/github-pages-deploy-action@4.4.0
        with:
          repository-name: practicalli/blog-staging
          token: ${{ secrets.CRYOGEN_PUBLISH_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: public/blog-staging # The folder the action should deploy.
          commit-message: ${{ github.event.head_commit.message }}
          single-commit: yes
